# Generated by Django 5.1.4 on 2026-03-29 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('agent_type', models.CharField(choices=[('chatbot', 'Chatbot'), ('assistant', 'Assistant'), ('analyzer', 'Analyzer'), ('automation', 'Automation'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents_agent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='agents_agen_slug_abaad8_idx'), models.Index(fields=['agent_type', 'is_active'], name='agents_agen_agent_t_df2b4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='agents.agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Usage Log',
                'verbose_name_plural': 'Agent Usage Logs',
                'db_table': 'agents_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'agent'], name='agents_usag_user_id_404edb_idx'), models.Index(fields=['action'], name='agents_usag_action_dc534c_idx'), models.Index(fields=['created_at'], name='agents_usag_created_a748ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAgentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='agents.agent')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Agent Access',
                'verbose_name_plural': 'User Agent Accesses',
                'db_table': 'agents_user_access',
                'indexes': [models.Index(fields=['user', 'is_active'], name='agents_user_user_id_644f39_idx'), models.Index(fields=['agent', 'is_active'], name='agents_user_agent_i_0d9490_idx'), models.Index(fields=['expires_at'], name='agents_user_expires_311b9e_idx')],
                'unique_together': {('user', 'agent')},
            },
        ),
    ]
