# Generated by Django 5.1.4 on 2026-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='efficiency',
            field=models.PositiveSmallIntegerField(default=100, help_text='Efficiency percentage (0–100)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='latency',
            field=models.CharField(choices=[('instant', 'Instant'), ('fast', 'Fast'), ('moderate', 'Moderate'), ('slow', 'Slow')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
