# Generated by Django 5.1.4 on 2026-03-29 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_efficiency_agent_latency_agent_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Group',
                'verbose_name_plural': 'Agent Groups',
                'db_table': 'agents_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentGroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_accesses', to='agents.agent')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_group_accesses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_accesses', to='agents.agentgroup')),
            ],
            options={
                'verbose_name': 'Group Agent Access',
                'verbose_name_plural': 'Group Agent Accesses',
                'db_table': 'agents_group_access',
                'indexes': [models.Index(fields=['group', 'is_active'], name='agents_grou_group_i_96a437_idx'), models.Index(fields=['agent', 'is_active'], name='agents_grou_agent_i_44e1f5_idx')],
                'unique_together': {('group', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='AgentGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='agents.agentgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'agents_group_membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='agents_grou_user_id_7fdc65_idx'), models.Index(fields=['group', 'is_active'], name='agents_grou_group_i_c9b044_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
