# Generated by Django 5.1.4 on 2026-05-02 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_system_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTimeLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limit_minutes', models.PositiveIntegerField(help_text='Max allowed minutes for this agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_limits', to='agents.agent')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_time_limits', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_time_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Time Limit',
                'verbose_name_plural': 'Agent Time Limits',
                'db_table': 'agents_time_limit',
                'indexes': [models.Index(fields=['target_user'], name='agents_time_target__3b7ba6_idx'), models.Index(fields=['agent', 'target_user'], name='agents_time_agent_i_01416c_idx')],
                'unique_together': {('agent', 'target_user')},
            },
        ),
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('seconds_active', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Session',
                'verbose_name_plural': 'Usage Sessions',
                'db_table': 'agents_usage_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'agent'], name='agents_usag_user_id_f7aaf9_idx'), models.Index(fields=['is_active'], name='agents_usag_is_acti_1c1d11_idx'), models.Index(fields=['started_at'], name='agents_usag_started_dfbf0b_idx')],
            },
        ),
    ]
