# Generated by Django 5.1.4 on 2026-04-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_managed_by_alter_customuser_role'),
        ('company', '0002_initial_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to. Set by admin or superadmin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.company'),
        ),
    ]
