# Generated by Django 5.1.4 on 2026-04-05 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Life Science AI', max_length=200)),
                ('location', models.TextField(default='Level 1, 9 The Esplanade, Perth WA 6000, Australia')),
                ('website', models.URLField(default='lifescienceai.com.au')),
                ('email', models.EmailField(default='connect@lifescienceai.com.au', max_length=254)),
                ('timezone', models.CharField(default='Perth, Australia (AWST, UTC+8)', max_length=100)),
                ('mission', models.TextField(blank=True, default='Empower professionals and organisations with practical AI tools...')),
                ('pillars', models.JSONField(blank=True, default=list, help_text='List of company pillars')),
                ('services', models.JSONField(blank=True, default=list, help_text='List of services offered')),
                ('who_we_serve', models.JSONField(blank=True, default=list, help_text='List of target audiences')),
                ('process', models.JSONField(blank=True, default=list, help_text='Company process steps')),
                ('system_prompt', models.TextField(blank=True, default='You are AVA — the AI Reception & Inquiry Assistant for Life Science AI...', help_text='System prompt for AI assistant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, help_text='Admin who can manage this company info. Null = superadmin only', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company_company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timezone', models.CharField(default='Perth (AWST)', max_length=100)),
                ('format', models.CharField(default='Interactive workshop', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_by', models.ForeignKey(blank=True, help_text='Admin who can manage this event. Null = superadmin only', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'company_event',
                'ordering': ['date', 'time'],
            },
        ),
    ]
