# Generated by Django 5.1.4 on 2026-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orgintegrationcredential',
            new_name='integ_cred_org_active_idx',
            old_name='integrations_cred_org_active_idx',
        ),
        migrations.AlterField(
            model_name='orgintegrationcredential',
            name='extra_data',
            field=models.TextField(blank=True, help_text='Fernet-encrypted JSON with provider-specific extras (workspace_id etc.)'),
        ),
    ]
