# Generated by Django 5.1.4 on 2026-04-08 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentgroup_agentgroupaccess_agentgroupmembership'),
        ('organizations', '0002_seed_free_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orgagentaccess',
            index=models.Index(fields=['org', 'is_enabled'], name='orgagent_org_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='orgagentaccess',
            index=models.Index(fields=['agent', 'is_enabled'], name='orgagent_agent_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='useragentpermission',
            index=models.Index(fields=['user', 'agent', 'is_active'], name='uap_user_agent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='useragentpermission',
            index=models.Index(fields=['org', 'is_active'], name='uap_org_active_idx'),
        ),
    ]
