# Generated by Django 5.1.4 on 2026-04-11 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentgroup_agentgroupaccess_agentgroupmembership'),
        ('organizations', '0003_orgagentaccess_orgagent_org_enabled_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracker', models.CharField(blank=True, max_length=50)),
                ('available_projects', models.JSONField(blank=True, default=list)),
                ('last_project_key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('projects_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('projects_stale', models.BooleanField(default=True)),
                ('messenger', models.CharField(blank=True, max_length=50)),
                ('default_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_configs', to='agents.agent')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Org Agent Config',
                'verbose_name_plural': 'Org Agent Configs',
                'db_table': 'organizations_org_agent_config',
                'constraints': [models.UniqueConstraint(fields=('org', 'agent'), name='unique_org_agent_config')],
            },
        ),
    ]
