# Generated by Django 5.1.4 on 2026-04-11 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_orgagentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('agent_slug', models.CharField(blank=True, max_length=180)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('tracker', models.CharField(blank=True, max_length=50)),
                ('messenger', models.CharField(blank=True, max_length=50)),
                ('default_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('available_projects', models.JSONField(blank=True, default=list)),
                ('last_project_key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('projects_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Agent Session',
                'verbose_name_plural': 'Agent Sessions',
                'db_table': 'organizations_agent_session',
                'indexes': [models.Index(fields=['org', 'agent_slug'], name='session_org_agent_idx')],
            },
        ),
    ]
