# Generated by Django 5.1.3 on 2026-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_orgagentaccess_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='crm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='crm_creds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orgagentconfig',
            name='crm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orgagentconfig',
            name='crm_creds',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
